//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 11:04:47 PM CST 
//


package com.csb.common.manifest;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cordsInfrastructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cordsInfrastructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="compute" type="{http://www.compatibleone.fr/schemes/manifest.xsd}cordsCompute"/&gt;
 *         &lt;element name="network" type="{http://www.compatibleone.fr/schemes/manifest.xsd}cordsNetwork"/&gt;
 *         &lt;element name="storage" type="{http://www.compatibleone.fr/schemes/manifest.xsd}cordsStorage"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="compute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="network" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="storage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cordsInfrastructure", propOrder = {
    "compute",
    "network",
    "storage"
})
public class CordsInfrastructure {

    @XmlElement(required = true)
    protected CordsCompute compute;
    @XmlElement(required = true)
    protected CordsNetwork network;
    @XmlElement(required = true)
    protected CordsStorage storage;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "compute")
    protected String computeAtt;
    @XmlAttribute(name = "network")
    protected String networkAtt;
    @XmlAttribute(name = "storage")
    protected String storageAtt;
    @XmlAttribute(name = "state")
    protected BigInteger state;

    /**
     * Gets the value of the compute property.
     * 
     * @return
     *     possible object is
     *     {@link CordsCompute }
     *     
     */
    public CordsCompute getCompute() {
        return compute;
    }

    /**
     * Sets the value of the compute property.
     * 
     * @param value
     *     allowed object is
     *     {@link CordsCompute }
     *     
     */
    public void setCompute(CordsCompute value) {
        this.compute = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link CordsNetwork }
     *     
     */
    public CordsNetwork getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link CordsNetwork }
     *     
     */
    public void setNetwork(CordsNetwork value) {
        this.network = value;
    }

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link CordsStorage }
     *     
     */
    public CordsStorage getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CordsStorage }
     *     
     */
    public void setStorage(CordsStorage value) {
        this.storage = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the computeAtt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComputeAtt() {
        return computeAtt;
    }

    /**
     * Sets the value of the computeAtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComputeAtt(String value) {
        this.computeAtt = value;
    }

    /**
     * Gets the value of the networkAtt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkAtt() {
        return networkAtt;
    }

    /**
     * Sets the value of the networkAtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkAtt(String value) {
        this.networkAtt = value;
    }

    /**
     * Gets the value of the storageAtt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageAtt() {
        return storageAtt;
    }

    /**
     * Sets the value of the storageAtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageAtt(String value) {
        this.storageAtt = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setState(BigInteger value) {
        this.state = value;
    }

}
