//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 11:04:47 PM CST 
//


package com.csb.common.manifest;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cordsImage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cordsImage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="system" type="{http://www.compatibleone.fr/schemes/manifest.xsd}cordsSystem"/&gt;
 *         &lt;element name="package" type="{http://www.compatibleone.fr/schemes/manifest.xsd}cordsPackage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="system" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="vm" type="{http://www.w3.org/2001/XMLSchema}string" default="cordscript: vm.new(id.value,provider.value); vm.build();" /&gt;
 *       &lt;attribute name="agent" type="{http://www.w3.org/2001/XMLSchema}string" default="cosacs" /&gt;
 *       &lt;attribute name="packages" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cordsImage", propOrder = {
    "system",
    "_package"
})
public class CordsImage {

    @XmlElement(required = true)
    protected CordsSystem system;
    @XmlElement(name = "package")
    protected List<CordsPackage> _package;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "system")
    protected String systemAtt;
    @XmlAttribute(name = "vm")
    protected String vm;
    @XmlAttribute(name = "agent")
    protected String agent;
    @XmlAttribute(name = "packages")
    protected BigInteger packages;
    @XmlAttribute(name = "state")
    protected BigInteger state;

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link CordsSystem }
     *     
     */
    public CordsSystem getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link CordsSystem }
     *     
     */
    public void setSystem(CordsSystem value) {
        this.system = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CordsPackage }
     * 
     * 
     */
    public List<CordsPackage> getPackage() {
        if (_package == null) {
            _package = new ArrayList<CordsPackage>();
        }
        return this._package;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the systemAtt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemAtt() {
        return systemAtt;
    }

    /**
     * Sets the value of the systemAtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemAtt(String value) {
        this.systemAtt = value;
    }

    /**
     * Gets the value of the vm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVm() {
        if (vm == null) {
            return "cordscript: vm.new(id.value,provider.value); vm.build();";
        } else {
            return vm;
        }
    }

    /**
     * Sets the value of the vm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVm(String value) {
        this.vm = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgent() {
        if (agent == null) {
            return "cosacs";
        } else {
            return agent;
        }
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgent(String value) {
        this.agent = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPackages(BigInteger value) {
        this.packages = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setState(BigInteger value) {
        this.state = value;
    }

}
