//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.14 at 09:58:28 PM CST 
//


package com.csb.common.saas.manifest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.csb.common.saas.manifest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Manifest_QNAME = new QName("http://www.compatibleone.fr/schemes/saas-manifest.xsd", "manifest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.csb.common.saas.manifest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssignmentType }
     * 
     */
    public AssignmentType createAssignmentType() {
        return new AssignmentType();
    }

    /**
     * Create an instance of {@link SaasManifest }
     * 
     */
    public SaasManifest createSaasManifest() {
        return new SaasManifest();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link ModulesType }
     * 
     */
    public ModulesType createModulesType() {
        return new ModulesType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link CreatorType }
     * 
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link CustomeAttributesType }
     * 
     */
    public CustomeAttributesType createCustomeAttributesType() {
        return new CustomeAttributesType();
    }

    /**
     * Create an instance of {@link CustomeAttributeType }
     * 
     */
    public CustomeAttributeType createCustomeAttributeType() {
        return new CustomeAttributeType();
    }

    /**
     * Create an instance of {@link AssignmentType.User }
     * 
     */
    public AssignmentType.User createAssignmentTypeUser() {
        return new AssignmentType.User();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaasManifest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.compatibleone.fr/schemes/saas-manifest.xsd", name = "manifest")
    public JAXBElement<SaasManifest> createManifest(SaasManifest value) {
        return new JAXBElement<SaasManifest>(_Manifest_QNAME, SaasManifest.class, null, value);
    }

}
